apps/articulo/urls.py
from django.urls import  path

from apps.comentario.views import  registrarComentario, registrarRespuestaAComentario
from .views import  ArticuloBusquedaView, ArticuloListView, ArticuloResumidoView, AutorListView, BorrarArticuloView, BorrarCategoriaView, CategoriaListView, ArticuloView,  CrearArticulo, CrearCategoria, EditarArticulo

app_name = 'articulo'

urlpatterns = [
    path('articulos/', ArticuloListView.as_view(), name='articulos'),
    path('articulo/<int:id>/',ArticuloView.as_view(), name='mostrarArticulo'),
    path('articulo/crear/',CrearArticulo.as_view(), name='crear'),
    path('articulo_resumido/<int:id>/',ArticuloResumidoView.as_view(), name='articulo_resumido'),
    path('articulo/<int:id>/comentar/', registrarComentario, name='comentar'),
    path('articulo/<int:pk>/editar/', EditarArticulo.as_view(), name='editar'),
    path('categoria/<int:pk>/', CategoriaListView.as_view(), name='categoria'),
    path('autor/<int:pk>/', AutorListView.as_view(), name='autor'),
    path('articulo/buscar/',ArticuloBusquedaView.as_view(), name='buscar'),
    path('articulo/<int:id>/responder/', registrarRespuestaAComentario, name='responder'),
    path('categoria/crear/', CrearCategoria.as_view(), name='crearCategoria'),
    path('categoria/<int:pk>/borrar/', BorrarCategoriaView.as_view(), name='borrarCategoria'),
    path('articulo/<int:pk>/borrar/', BorrarArticuloView.as_view(), name='borrar'),
]

apps/comentario/urls.py
from django.urls import  path

from .views import  BorrarComentarioView, EditarComentario

app_name = 'comentario'

urlpatterns = [
    path('comentario/<int:pk>/editar/', EditarComentario.as_view(), name='editar'),
    path('comentario/<int:pk>/borrar/', BorrarComentarioView.as_view(), name='borrar'),
]

apps/contacto/urls.py
from django.urls import path

from apps.contacto.views import BorrarContactoView, ContactoUsuario, DetalleContactoView, ListarContactosView

app_name = 'contacto'

urlpatterns = [
    path('contacto/', ContactoUsuario.as_view(), name='contacto'),
    path('contactos/ver/', ListarContactosView.as_view(), name='verContactos'),
    path('contacto/<int:pk>/ver/', DetalleContactoView.as_view(), name='detalle'),
    path('contacto/<int:pk>/borrar/', BorrarContactoView.as_view(), name='borrar')
]

apps/usuario/urls.py
from django.urls import  path
from django.contrib.auth.decorators import permission_required
from apps.usuario.views import CambiarEstadoView, CambiarRolView, LoginUsuario, LogoutUsuario, UpdateUsuarioView, VerUsuariosView, registrarUsuario, VerPerfilUsuario


app_name = 'usuario'

urlpatterns = [
    path('usuario/registro/', registrarUsuario.as_view(), name = 'registro'),
    path('usuario/login/', LoginUsuario.as_view(), name='login'),
    path('usuario/logout/', LogoutUsuario.as_view(), name='logout'),
    path('usuario/<int:pk>/actualizar/', UpdateUsuarioView.as_view(), name="actualizar"),
    path('usuario/<int:pk>/ver_perfil/', VerPerfilUsuario.as_view(), name="perfil"),
    path('usuario/usuarios/', VerUsuariosView.as_view(), name="usuarios"),
    path('usuario/estado/<int:pk>', CambiarEstadoView.as_view(), name="cambiar_estado"),
    path('usuario/cambiarrol/<int:pk>', CambiarRolView.as_view(), name="cambiar_rol"),
]

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from .views import IndexView, registration_success, sobre_nosotros

urlpatterns = [
    path('jpqifepfnapkjdfnapdjk/', admin.site.urls),
    path('',IndexView.as_view(), name = "inicio"),
    path('nosotros/', sobre_nosotros, name="nosotros"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("acounts/registration/success/",registration_success, name='registration_success'),
    path('', include('apps.articulo.urls')),
    path('', include('apps.usuario.urls')),
    path('', include('apps.comentario.urls')),
    path('', include('apps.contacto.urls')),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuario/models.py
from django.contrib.auth.models import Group, User, Permission
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy

import datetime

# Create your models here.


class Usuario(AbstractUser):
    is_miembro = models.BooleanField(default=False)
    foto_perfil = models.ImageField(upload_to="usuario",
        default="../static/default-user.png"
        )
    fecha_nacimiento = models.DateField(
        null=True,
        blank=True
    )


    def get_link_verperfil(self):
        return reverse_lazy('usuario:perfil', args=[ self.pk ])

    def get_edad(self):
        return int((datetime.date.today() - self.fecha_nacimiento).days / 365.25)

    def __str__(self):
        return self.username

apps/usuario/forms.py
from typing import Any, Dict
from django.forms import CharField, DateField, ModelForm, PasswordInput
from django.contrib.auth.decorators import login_required
from apps.usuario.models import Usuario


class UserCreationForm(ModelForm):
    password = CharField(
        label='Contraseña', 
        widget=PasswordInput(
            attrs={'placeholder': 'Contraseña'}
            ), 
        required=True)
    password2 = CharField(
        label='Reingrese Contraseña', 
        widget=PasswordInput(
            attrs={'placeholder': 'Reingrese su contraseña'}
            ), 
        required=True)
    fecha_nacimiento = DateField(
        label="Ingrese fecha de nacimiento"
    )
    
    def clean(self):
        cleaned_form = super().clean() 
        password = cleaned_form.get('password')
        password2 = cleaned_form.get('password2')
        if password != password2:
            self.add_error("password2", "Las contraseñas no coinciden")
        return cleaned_form
    
    class Meta:
        model = Usuario
        fields = ('username', 'first_name','last_name','foto_perfil','email','fecha_nacimiento', 'password')



class UserEditionForm(ModelForm):

    fecha_nacimiento = DateField(
        label="Ingrese fecha de nacimiento"
    )
    
    def clean(self):
        return super().clean() 
    
    class Meta:
        model = Usuario
        fields = ('first_name','last_name','foto_perfil','email','fecha_nacimiento')

apps/usuario/views.py
from typing import Any, Dict
from django import http
from django.contrib.auth.forms import AuthenticationForm
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.utils.http import url_has_allowed_host_and_scheme


from apps.articulo.models import Articulo
from apps.comentario.models import Comentario
from apps.usuario.forms import UserCreationForm, UserEditionForm
from apps.usuario.models import Usuario



class registrarUsuario(CreateView):

    template_name = 'registration/registro.html'
    form_class = UserCreationForm
    model = Usuario

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['next'] = self.request.GET.get('next', '')
        return ctx

    def form_valid(self, form):
        if form.is_valid():
            usuario = form.save(commit=False)
            usuario.password = make_password(form.cleaned_data["password"])
            usuario.save()
            usuario = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password'],
                                    )
            login(self.request, usuario)
            return super().form_valid(form)
        else:
            self.form_invalid(form)

    def get_success_url(self) -> str:
        redirect_to = self.request.POST.get('next', '')
        messages.warning(self.request, redirect_to)
        url_is_safe = url_has_allowed_host_and_scheme(redirect_to, '*')
        if redirect_to and url_is_safe:
            messages.success(self.request, "¡Usuario creado correctamente!")
            return redirect_to



class LoginUsuario(UserPassesTestMixin,LoginView):

    def test_func(self):
        if self.request.user.is_authenticated:
            return False
        else:
            return True

    def handle_no_permission(self):
        return redirect(reverse_lazy('usuario:logout'))

    def form_valid(self, form):
        if form.is_valid():
            return super().form_valid(form)
        else:
            self.form_invalid(form)

    def form_invalid(self, form: AuthenticationForm):
        messages.warning(self.request, "¡Usuario o contraseña incorrectos, intente nuevamente!")
        return super().form_invalid(form)

    def get_success_url(self) -> str:
        redirect_to = self.request.POST.get('next', '')
        url_is_safe = url_has_allowed_host_and_scheme(redirect_to, '*')
        if redirect_to != None and url_is_safe:
            messages.success(self.request, "¡Usuario logueado correctamente!")
            return redirect_to

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        next = self.request.GET.get('next','')
        context['next'] = next
        return context



class LogoutUsuario(LoginRequiredMixin, LogoutView):

    def handle_no_permission(self):
        return redirect(reverse_lazy('usuario:login'))

    def get(self, request, *args: Any, **kwargs) -> HttpResponse:
        messages.success(self.request, "¡Sesion cerrada correctamente!")
        return super().get(request, *args, **kwargs)



class UpdateUsuarioView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    template_name = "usuario/editarperfil.html"
    model = Usuario
    form_class = UserEditionForm

    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser or self.request.user == self.get_object()):
            return True
        else:
            return False

    def get_success_url(self) -> str:
        redirect_to = self.request.POST.get('next', '')
        url_is_safe = url_has_allowed_host_and_scheme(redirect_to, '*')
        if redirect_to != None and url_is_safe:
            messages.success(self.request, "¡Usuario actualizado correctamente!")
            return redirect_to

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['usuario'] = self.get_object(self.queryset)
        next = self.request.GET.get('next','')
        context['next'] = next
        return context

    def form_valid(self, form):
        if form.is_valid():
            messages.success(self.request, "¡Usuario actualizado correctamente!")
            return super().form_valid(form)
        else:
            self.form_invalid(form)




class VerPerfilUsuario(DetailView):
    model = Usuario
    template_name = 'usuario/perfil.html'
    context_object_name = 'usuario'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        articulos = Articulo.objects.filter(creado_por=kwargs['object'])
        comentarios = Comentario.objects.filter(creado_por=kwargs['object'])
        cant_comentarios = comentarios.count()
        cant_articulos = articulos.count()
        if cant_comentarios == 0:
            titulo_comentarios = 'Sin comentarios'
        elif cant_comentarios == 1:
            titulo_comentarios = '1 Comentario'
        else:
            titulo_comentarios = str(cant_comentarios) + ' ' + 'Comentarios'
        if cant_articulos == 0:
            titulo_articulos = 'Sin articulos'
        elif cant_articulos == 1:
            titulo_articulos = '1 Articulo'
        else:
            titulo_articulos = str(cant_comentarios) + ' ' + 'Articulos'
        ctx['titulo_articulos'] = titulo_articulos
        ctx['titulo_comentarios'] = titulo_comentarios
        ctx['comentarios'] = comentarios
        ctx['articulos'] = articulos
        return ctx



class VerUsuariosView(LoginRequiredMixin, UserPassesTestMixin, ListView):

    model = Usuario
    template_name = 'usuario/usuarios.html'
    context_object_name = 'usuarios'
    paginate_by = 10

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        cantidad_usuarios = Usuario.objects.count()
        context['cantidad_usuarios'] = cantidad_usuarios
        return context

    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False


class CambiarEstadoView(LoginRequiredMixin, UserPassesTestMixin, View):

    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    def dispatch(self, request, *args, **kwargs):
        if request.method == "GET":
            success_url = request.GET.get('next')
            usuario = Usuario.objects.get(id=kwargs['pk'])
            if usuario != self.request.user:
                usuario.is_active = not usuario.is_active
                usuario.save()
                estado = "activo" if usuario.is_active else "suspendido"
                messages.success(request, "Se cambio estado de " + str(usuario) + " a " + estado)
            else:
                messages.warning(request, "Usted no puede cambiar su propio estado")
            return redirect(success_url)
        else:
            return redirect(success_url)

class CambiarRolView(LoginRequiredMixin, UserPassesTestMixin, View):

    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    def dispatch(self, request, *args, **kwargs):
        if request.method == "GET":
            success_url = request.GET.get('next')
            usuario = Usuario.objects.get(id=kwargs['pk'])
            if usuario != self.request.user:
                usuario.is_miembro = not usuario.is_miembro
                estado = "colaborador" if usuario.is_miembro else "visitante"
                usuario.save()
                messages.success(request, "Se cambio rol de " + str(usuario) + " a " + estado)
            else:
                messages.warning(request, "Usted no puede cambiar su rol")
            return redirect(success_url)
        else:
            return redirect(success_url)

templates/usuario/editar_perfil.html
{% extends "index.html"%}
{% block title %} Blog G13 - Perfil {{usuario}} {% endblock %}
{% block contenido %}
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>PERFIL</span>
              <h4>Estas viendo el perfil de: <em>{{usuario}}</em></h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="blog-posts">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="blog-posts">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item submit-comment">
                <div class="content">
                  <div class="row">
                    <div class="col-6">
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        {{form.non_field_errors}}
                        <input type="hidden" value="{{ next }}" name="next">
                        <button type="submit" style="width:100%;" >Actualizar perfil</button>
                      </form>
                    </div>
                    <div class="col-6">
                      <p class="">Foto de perfil:</p>
                      <div class="circular--profile">
                        <img id="imagePreviewOne" class="" style="display:none;"/>
                        <img id="id_foto_actual" class="" src="{{usuario.foto_perfil.url}}"/>
                    </div>
                  </div>
                  <hr>
                  <a href="{% url 'inicio' %}">volver</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
  id_foto_perfil.onchange = evt => {
  imagePreviewOne.style.display = "inline";
  id_foto_actual.style.display = "none"
  const [file] = id_foto_perfil.files
  console.log(id_foto_perfil.files)
  if (file) {
    imagePreviewOne.src = URL.createObjectURL(file)
  } else {
    imagePreviewOne.style.display = "none";
  }
}
</script>
{% endblock %}

templates/usuario/perfil.html
{% extends "index.html"%}
{% block title %} Blog G13 - Perfil {{usuario}} {% endblock %}
{% block contenido %}
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>PERFIL</span>
              <h4>Estas viendo el perfil de: <em>{{usuario}}</em></h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="blog-posts">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="blog-posts">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item submit-comment">
                <div class="content">
                  <div class="row">
                    <div class="col-lg-6">
                      <table class="table">
                        <tr>
                          <td><h5>Nombre:</h5></td>
                          <td>{{usuario.first_name}}</td>
                        </tr>
                        <tr>
                          <td><h5>Apellido:</h5></td>
                          <td>{{usuario.last_name}}</td>
                        </tr>
                        <tr>
                          <td><h5>Fecha de nacimiento:</h5></td>
                          <td>{{usuario.fecha_nacimiento}}</td>
                        </tr>
                        <tr>
                          {% if usuario.fecha_nacimiento %}
                          <td><h5>Edad:</h5></td>
                          <td>{{usuario.get_edad}}</td>
                          {% endif %}
                        </tr>
                        <tr>
                          <td><h5>Email:</h5></td>
                          <td>{{usuario.email}}</td>
                        </tr>
                        <tr>
                          <td><h5>Registrado:</h5></td>
                          <td>{{usuario.date_joined}}</td>
                        </tr>
                      </table>

                      <p>
                      <div class="row">
                        <div class="col-lg-12">
                        {% if user.is_miembro or user.is_superusuario or user == usuario %}
                          <a href="{% url 'usuario:actualizar' pk=usuario.pk %}?next={{request.path}}">
                            <button>EDITAR PERFIL</button>
                          </a>
                        {% if user.is_miembro or user.is_superuser %}
                          <a href="{% url 'contacto:verContactos' %}">
                            <button>ver mensajes</button>
                          </a>
                          <a href="{% url 'usuario:usuarios' %}">
                            <button>ver usuarios</button>
                          </a>
                        {% endif %}
                        {% endif %}
                        </div>
                      </div>
                      </p>
                    </div>
                    <div class="col-lg-6">
                      <p>Foto de perfil:</p>
                      <div class="circular--profile center">
                        <img src="{{usuario.foto_perfil.url}}" alt="foto perfil {{usuario}}">
                      </div>
                      <br>
                      <br>
                  </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-lg-6">
                      <h3>{{articulos|length}} articulos</h3>
                      <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                          <thead class="table-dark">
                            <tr>
                              <th scope="col">Fecha</th>
                              <th scope="col">Titulo</th>
                              <th scope="col">link</th>
                              {% if user.is_superuser or user.is_miembro %}
                              <th colspan="2">edicion</th>
                              {% endif %}
                            </tr>
                          </thead>
                          <tbody>
                          {% for articulo in articulos %}
                            <tr>
                              <td>{{articulo.fecha}}</td>
                              <td>{{articulo.titulo}}</td>
                              <td><a href="{{articulo.get_url_completo}}">ver articulo</a></td>
                              {% if user.is_superuser or user.is_miembro %}
                              <td><a href="{% url 'articulo:editar' pk=articulo.pk %}?next={{request.path}}"><i class="fa-xl fa-solid fa-pencil center"></i></a></td>
                              <td><a href="{% url 'articulo:borrar' pk=articulo.pk %}?next={{request.path}}"><i class="fa-xl fa-solid fa-trash danger center"></i></a></td>
                              {% endif %}
                            </tr>
                          {% empty %}
                            <tr>
                              <td colspan="5">No ha publicado articulos</td>
                            </tr>
                          {% endfor %}
                        </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <h3>{{titulo_comentarios}}</h3>
                      <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                          <thead class="table-dark">
                            <tr>
                              <th scope="col">Fecha</th>
                              <th scope="col">contenido</th>
                              <th scope="col">comenta</th>
                              <th scope="col">link</th>
                              {% if user.is_superuser or user.is_miembro %}
                              <th colspan="2">edicion</th>
                              {% endif %}
                            </tr>
                          </thead>
                          <tbody>
                          {% for comentario in comentarios %}
                            <tr>
                              <td>{{comentario.creado}}</td>
                              <td>{{comentario.contenido}}</td>
                              {% if comentario.articulo %}
                              <td>{{comentario.articulo}}</td>
                              <td><a href="{{comentario.articulo.get_url_completo}}">ver articulo</a></td>
                              {% else %}
                              <td>{{comentario.comentario_padre}}</td>
                              <td><a href="{{comentario.comentario_padre.articulo.get_url_completo}}">ver articulo</a></td>
                              {% endif %}
                              {% if user.is_superuser or user.is_miembro %}
                              <td><a href="{% url 'comentario:editar' pk=comentario.pk %}?next={{request.path}}"><i class="fa-xl fa-solid fa-pencil center"></i></a></td>
                              <td><a href="{% url 'comentario:borrar' pk=comentario.pk %}?next={{request.path}}"><i class="fa-xl fa-solid fa-trash danger center"></i></a></td>
                              {% endif %}
                            </tr>
                          {% empty %}
                            <tr>
                              <td colspan="5">No ha publicado comentarios</td>
                            </tr>
                          {% endfor %}
                        </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <a href="{% url 'inicio' %}">volver</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/usuario/usuarios.html
{% extends "index.html"%}
{% load articulo_tags %}
{% block title %} Blog G13 - Perfil {{usuario}} {% endblock %}
{% block contenido %}
<style>
  .usuario {
    background-color: rgb(212, 236, 193);
    color: #f48840;
  }
</style>
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>USUARIOS</span>
              <h4>Estas viendo todos los usuarios</h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="blog-posts">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="blog-posts">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item submit-comment">
                <div class="content">
                  <div class="row">
                    <div class="col-sm-12">
                      <h5>{{cantidad_usuarios}} usuarios registrados</h5>
                      <div class="col-sm-12">
                      <ul class="page-numbers">
                        {% if page_obj.has_previous %}
                        <li>
                          <a href="?page=1">
                            <i class="fa-solid fa-xl fa-angles-left"></i>
                          </a>
                          <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                        </li>
                        {% endif %}
                        <li class="active">
                          <a href="">{{ page_obj.number }}</a>
                        </li>
                        {% if page_obj.has_next %}
                        <li>
                          <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                          <a href="?page={{ page_obj.paginator.num_pages }}" sytle="color:orange;"><i class="fa-solid fa-xl fa-angles-right"></i></a>
                        </li>
                        {% endif %}
                      </ul>
                    </div>
                    </div>
                      <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                          <thead class="table-dark">
                            <tr style="text-align: center;">
                              <th scope="col">ID</th>
                              <th scope="col">Nombre usuario</th>
                              <th scope="col">e-mail</th>
                              <th scope="col">fecha registro</th>
                              <th scope="col">ultima actividad</th>
                              <th scope="col">editar</th>
                              <th scope="col">rol</th>
                              <th scope="col">activo</th>
                              <th scope="col">cambiar estado</th>
                            </tr>
                          </thead>
                          <tbody>
                          {% for usuario in usuarios %}
                            <tr  style="text-align: center;" class="{% if user == usuario %}usuario{% endif %}">
                              <td>{{usuario.id}}</td>
                              <td>{{usuario.username}}</td>
                              <td>{{usuario.email}}</td>
                              <td>{{usuario.date_joined}}</td>
                              <td>{{usuario.last_login}}</td>
                              <td><a href="{% url 'usuario:actualizar' pk=usuario.pk %}?next={{request.get_full_path}}">editar</a></td>
                              {% if user != usuario %}
                              <td><a href="{% url 'usuario:cambiar_rol' pk=usuario.pk %}?next={{request.get_full_path}}">{{usuario|rol}}</a></td>
                              <td>{{usuario.is_active|si_no}}</td>
                              <td>
                                <a href="{% url 'usuario:cambiar_estado' pk=usuario.pk %}?next={{request.get_full_path}}">
                                {% if usuario.is_active %}
                                  suspender
                                {% else %}
                                  habilitar
                                {% endif %}
                                </a>
                              </td>
                              {% else %}
                              <td colspan="3" style="text-align: center;">Usuario actual</td>
                              {% endif %}
                            </tr>
                          {% empty %}
                            <tr>
                              <td colspan="5">No hay usuarios</td>
                            </tr>
                          {% endfor %}
                        </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <a href="{% url 'inicio' %}">volver</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}