apps/contacto/urls.py
from django.urls import path

from apps.contacto.views import BorrarContactoView, ContactoUsuario, DetalleContactoView, ListarContactosView

app_name = 'contacto'

urlpatterns = [
    path('contacto/', ContactoUsuario.as_view(), name='contacto'),
    path('contactos/ver/', ListarContactosView.as_view(), name='verContactos'),
    path('contacto/<int:pk>/ver/', DetalleContactoView.as_view(), name='detalle'),
    path('contacto/<int:pk>/borrar/', BorrarContactoView.as_view(), name='borrar')
]

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from .views import IndexView, registration_success, sobre_nosotros

urlpatterns = [
    path('jpqifepfnapkjdfnapdjk/', admin.site.urls),
    path('',IndexView.as_view(), name = "inicio"),
    path('nosotros/', sobre_nosotros, name="nosotros"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("acounts/registration/success/",registration_success, name='registration_success'),
    path('', include('apps.articulo.urls')),
    path('', include('apps.usuario.urls')),
    path('', include('apps.comentario.urls')),
    path('', include('apps.contacto.urls')),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contacto/models.py
from django.db import models
from django.utils import timezone

class Contacto(models.Model):
    nombre_apellido = models.CharField(max_length=120)
    email = models.EmailField()
    asunto = models.CharField(max_length=50)
    mensaje = models.TextField()
    fecha = models.DateTimeField(default =timezone.now)

    def __str__(self):
        return self.nombre_apellido

apps/contacto/forms.py
from django.forms import EmailField, ModelForm
from django.core import validators

from apps.contacto.models import Contacto


class ContactoForm(ModelForm):
    
    email = EmailField(
        validators=[validators.EmailValidator(message='Ingrese un email válido.')]
        )
    
    class Meta:
        model= Contacto
        fields = ('nombre_apellido', 'email', 'asunto', 'mensaje')

        

apps/contacto/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages

from apps.contacto.forms import ContactoForm
from apps.contacto.models import Contacto



class ContactoUsuario(CreateView):
    
    form_class = ContactoForm
    success_url = reverse_lazy('inicio')
    template_name = 'contacto/contacto.html'
    def form_valid(self, form):
        messages.success(self.request, "Mensaje enviado exitosamente!")
        return super().form_valid(form)
    


class ListarContactosView(UserPassesTestMixin, LoginRequiredMixin, ListView):

    model = Contacto
    template_name = 'contacto/contacto_lista.html'
    context_object_name = 'contactos'
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False



class DetalleContactoView(UserPassesTestMixin, LoginRequiredMixin, DetailView):
    
    model = Contacto
    template_name = 'contacto/contacto_detalle.html'
    context_object_name = 'contacto'
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False


class BorrarContactoView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    model = Contacto
    template_name = 'contacto/contacto_borrar.html'
    success_url = reverse_lazy('contacto:verContactos')

    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    def get_success_url(self) -> str:
        messages.success(self.request, "Contacto borrado exitosamente")
        return super().get_success_url()   
        
   

templates/contacto/contacto.html
{% extends "index.html" %}
{% block contacto_nav %} 
<li class="nav-item active">
{% endblock %}
{% block contenido %}    
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>CONTACTENOS</span>
              <h4>Gracias por comunicarse con nosotros<p></p></h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="contact-us">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="down-contact">
          <div class="row">
            <div class="col-lg-8">
              <div class="sidebar-item contact-form">
                <div class="sidebar-heading">
                  <h2>Envianos un mensaje</h2>
                </div>
                <div class="content">
                  <form id="contact" action="{% url 'contacto:contacto' %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                      <div class="col-lg-12">
                        {{form.as_p}}
                      </div>
                    </fieldset>
                    <fieldset>
                      <button type="submit" id="form-submit" class="main-button">Enviar mensaje</button>
                    </fieldset>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="sidebar-item contact-information">
                <div class="sidebar-heading">
                  <h2>información de contacto</h2>
                </div>
                <div class="content">
                  <ul>
                    <li>
                      <h5>+54-9-362444444</h5>
                      <span>NUMERO DE TELEFONO</span>
                    </li>
                    <li>
                      <h5>informatorio@informatorio.com.ar</h5>
                      <span>CORREO ELECTRONICO</span>
                    </li>
                    <li>
                      <h5>123 Aenean id posuere dui, 
                        <br>Praesent laoreet 10660</h5>
                      <span>DIRECCION</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="col-lg-12">
        <div id="map">
          <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
      </div> -->
    </div>
  </div>
</section>
{% endblock %}    

templates/contacto/contacto_borrar.html
{% extends "index.html"%}
{% block title %} Blog G13 - Borrar mensaje {% endblock %}
{% block contenido %}
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>Borrar</span>
              <h4>Usted esta por borrar el mensaje:</h4><p>{{object}}</p>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="blog-posts">
<div class="container">
    <div class="row">
    <div class="col-lg-12">
        <div class="all-blog-posts">
        <div class="row">
            <div class="col-lg-12">
            <div class="sidebar-item submit-comment">
                <div class="sidebar-heading">
                </div>
                  <div class="content">
                    <form method="post">{% csrf_token %}
                    <p>Estas seguro de que quieres borrar "{{ object }}"?</p>
                    <p>Esta accion es irreversible...</p>
                    {{ form }}
                    <button type="submit" id="form-submit" class="main-button">Eliminar</button>                    
                    </form>
                    <hr>
                  <a href="{% url 'contacto:verContactos' %}">volver</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/contacto/contacto_detalle.html
{% extends "index.html" %}
{% block contacto_nav %} 
<li class="nav-item active">
{% endblock %}
{% block contenido %}    
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>MENSAJES</span>
              <h4>Aqui se muestar el mensaje con ID: {{contacto.id}}<p></p></h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="contact-us">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="down-contact">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item contact-form">
                <div class="content">
                  <table class="table">
                    <tr>
                      <th><h5>ID:</h5></td>
                      <th><h5>Fecha</h5></td>
                      <th><h5>Nombre</h5></td>
                      <th><h5>Email</h5></td>
                      <th><h5>Eliminar</h5></td>
                    </tr>
                    <tr>
                      <td>{{contacto.id}}</td>
                      <td>{{contacto.fecha}}</td>
                      <td>{{contacto.nombre_apellido}}</td>
                      <td>{{contacto.email}}</td>
                      <td><a href="{% url 'contacto:borrar' pk=contacto.pk %}"><i class="fa-xl fa-solid fa-trash center"></i></a></td>
                    </tr>
                    <tr>
                      <td>Asunto:</td>
                      <td colspan="5">{{contacto.asunto}}</td>
                    </tr>
                    <tr>
                      <td>Mensaje:</td>
                      <td colspan="5">{{contacto.mensaje}}</td>
                    </tr>
                  </table>
                </div>
              </div>            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}    

templates/contacto/contacto_lista.html
{% extends "index.html" %}
{% block contacto_nav %} 
<li class="nav-item active">
{% endblock %}
{% block contenido %}    
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>MENSAJES</span>
              <h4>Aqui se listan todos los mensajes recibidos<p></p></h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="contact-us">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="down-contact">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item contact-form">
                <div class="content">
                  <table class="table">
                    <tr>
                      <th><h5>ID:</h5></td>
                      <th><h5>Fecha:</h5></td>
                      <th><h5>Nombre:</h5></td>
                      <th><h5>email:</h5></td>
                      <th><h5>Asunto:</h5></td>
                    </tr>
                    {% for mensaje in contactos %}
                    <tr>
                      <td><a href="{% url 'contacto:detalle' pk=mensaje.id %}">{{forloop.counter}}</a></td>
                      <td>{{mensaje.fecha}}</td>
                      <td>{{mensaje.nombre_apellido}}</td>
                      <td>{{mensaje.email}}</td>
                      <td>{{mensaje.asunto}}</td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td colspan="6">No hay mensajes</td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}    