apps/articulo/urls.py
from django.urls import  path

from apps.comentario.views import  registrarComentario, registrarRespuestaAComentario
from .views import  ArticuloBusquedaView, ArticuloListView, ArticuloResumidoView, AutorListView, BorrarArticuloView, BorrarCategoriaView, CategoriaListView, ArticuloView,  CrearArticulo, CrearCategoria, EditarArticulo

app_name = 'articulo'

urlpatterns = [
    path('articulos/', ArticuloListView.as_view(), name='articulos'),
    path('articulo/<int:id>/',ArticuloView.as_view(), name='mostrarArticulo'),
    path('articulo/crear/',CrearArticulo.as_view(), name='crear'),
    path('articulo_resumido/<int:id>/',ArticuloResumidoView.as_view(), name='articulo_resumido'),
    path('articulo/<int:id>/comentar/', registrarComentario, name='comentar'),
    path('articulo/<int:pk>/editar/', EditarArticulo.as_view(), name='editar'),
    path('categoria/<int:pk>/', CategoriaListView.as_view(), name='categoria'),
    path('autor/<int:pk>/', AutorListView.as_view(), name='autor'),
    path('articulo/buscar/',ArticuloBusquedaView.as_view(), name='buscar'),
    path('articulo/<int:id>/responder/', registrarRespuestaAComentario, name='responder'),
    path('categoria/crear/', CrearCategoria.as_view(), name='crearCategoria'),
    path('categoria/<int:pk>/borrar/', BorrarCategoriaView.as_view(), name='borrarCategoria'),
    path('articulo/<int:pk>/borrar/', BorrarArticuloView.as_view(), name='borrar'),
]

apps/contacto/urls.py
from django.urls import path

from apps.contacto.views import BorrarContactoView, ContactoUsuario, DetalleContactoView, ListarContactosView

app_name = 'contacto'

urlpatterns = [
    path('contacto/', ContactoUsuario.as_view(), name='contacto'),
    path('contactos/ver/', ListarContactosView.as_view(), name='verContactos'),
    path('contacto/<int:pk>/ver/', DetalleContactoView.as_view(), name='detalle'),
    path('contacto/<int:pk>/borrar/', BorrarContactoView.as_view(), name='borrar')
]

apps/usuario/urls.py
from django.urls import  path
from django.contrib.auth.decorators import permission_required
from apps.usuario.views import CambiarEstadoView, CambiarRolView, LoginUsuario, LogoutUsuario, UpdateUsuarioView, VerUsuariosView, registrarUsuario, VerPerfilUsuario


app_name = 'usuario'

urlpatterns = [
    path('usuario/registro/', registrarUsuario.as_view(), name = 'registro'),
    path('usuario/login/', LoginUsuario.as_view(), name='login'),
    path('usuario/logout/', LogoutUsuario.as_view(), name='logout'),
    path('usuario/<int:pk>/actualizar/', UpdateUsuarioView.as_view(), name="actualizar"),
    path('usuario/<int:pk>/ver_perfil/', VerPerfilUsuario.as_view(), name="perfil"),
    path('usuario/usuarios/', VerUsuariosView.as_view(), name="usuarios"),
    path('usuario/estado/<int:pk>', CambiarEstadoView.as_view(), name="cambiar_estado"),
    path('usuario/cambiarrol/<int:pk>', CambiarRolView.as_view(), name="cambiar_rol"),
]

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from .views import IndexView, registration_success, sobre_nosotros

urlpatterns = [
    path('jpqifepfnapkjdfnapdjk/', admin.site.urls),
    path('',IndexView.as_view(), name = "inicio"),
    path('nosotros/', sobre_nosotros, name="nosotros"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("acounts/registration/success/",registration_success, name='registration_success'),
    path('', include('apps.articulo.urls')),
    path('', include('apps.usuario.urls')),
    path('', include('apps.comentario.urls')),
    path('', include('apps.contacto.urls')),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/comentario/models.py
from datetime import datetime
from typing import Iterable, Optional
from django.db import models
from apps.articulo.models import Articulo
from apps.usuario.models import Usuario

# Create your models here.

class Comentario(models.Model):
    
    contenido = models.CharField(
        max_length=200, 
        verbose_name='Texto', 
        help_text='Ingrese aqui su comentario',
        default = ''
        )
    articulo = models.ForeignKey(
        Articulo, 
        on_delete = models.CASCADE, 
        verbose_name = 'Articulo',
        null = True,
        blank = True
        )
    creado = models.DateTimeField(
        editable = False, 
        verbose_name = "Fecha de publicacion"
        )
    comentario_padre = models.ForeignKey(
        "self",
        on_delete = models.CASCADE, 
        verbose_name = 'Comentario',
        null = True,
        blank = True
        )
    creado_por = models.ForeignKey(
        Usuario,
        on_delete = models.CASCADE,
        null=True,
        blank=True,
        verbose_name="creador", 
    )
    is_active = models.BooleanField(
        default=True,
    )    
    
    def __str__(self) -> str:
        return self.contenido
    
    def save(self, *args, **kwargs):
        self.creado = datetime.now()
        return super().save(*args, **kwargs)

apps/contacto/models.py
from django.db import models
from django.utils import timezone

class Contacto(models.Model):
    nombre_apellido = models.CharField(max_length=120)
    email = models.EmailField()
    asunto = models.CharField(max_length=50)
    mensaje = models.TextField()
    fecha = models.DateTimeField(default =timezone.now)

    def __str__(self):
        return self.nombre_apellido

apps/contacto/forms.py
from django.forms import EmailField, ModelForm
from django.core import validators

from apps.contacto.models import Contacto


class ContactoForm(ModelForm):
    
    email = EmailField(
        validators=[validators.EmailValidator(message='Ingrese un email válido.')]
        )
    
    class Meta:
        model= Contacto
        fields = ('nombre_apellido', 'email', 'asunto', 'mensaje')

        

apps/contacto/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages

from apps.contacto.forms import ContactoForm
from apps.contacto.models import Contacto



class ContactoUsuario(CreateView):
    
    form_class = ContactoForm
    success_url = reverse_lazy('inicio')
    template_name = 'contacto/contacto.html'
    def form_valid(self, form):
        messages.success(self.request, "Mensaje enviado exitosamente!")
        return super().form_valid(form)
    


class ListarContactosView(UserPassesTestMixin, LoginRequiredMixin, ListView):

    model = Contacto
    template_name = 'contacto/contacto_lista.html'
    context_object_name = 'contactos'
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False



class DetalleContactoView(UserPassesTestMixin, LoginRequiredMixin, DetailView):
    
    model = Contacto
    template_name = 'contacto/contacto_detalle.html'
    context_object_name = 'contacto'
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False


class BorrarContactoView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    model = Contacto
    template_name = 'contacto/contacto_borrar.html'
    success_url = reverse_lazy('contacto:verContactos')

    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    def get_success_url(self) -> str:
        messages.success(self.request, "Contacto borrado exitosamente")
        return super().get_success_url()   
        
   

templates/banner.html
{% load articulo_tags %}
<div class="main-banner header-text">
  <h4 class="mb-5">Ultimas publicaciones</h4>
    <div class="container-fluid">
        <div class="owl-banner owl-carousel">
            {% for articulo in articulos_banner %}
            <div class="item">
                <img src="{{articulo.imagen.url}}" alt="Imagen {{articulo.titulo}}">
                <div class="orla">
                <div class="item-content">
                  <div class="main-content">
                    <div class="meta-category">
                      <a href="{% url 'articulo:categoria' pk=articulo.categoria.pk %}">
                      <span>{{articulo.categoria}}</span></a>
                    </div>
                    <a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}">
                      <h4>{{articulo.titulo}}</h4>
                    </a>
                    <ul class="post-info">
                      <li><a href="{% url 'usuario:perfil' pk=articulo.creado_por.id  %}">{{articulo.creado_por}}</a></li>
                      <li><a href="">{{articulo.fecha}}</a></li>
                      <li><a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}">
                      {% if articulo.comentario_set.all|is_active|length == 0 %}
                      sin comentarios
                      {% else %}
                      {{articulo.comentario_set.all|is_active|length}} {%if articulo.comentario_set.all|is_active|length == 1%}comentario{%else%}comentarios{%endif%}
                      {% endif %}
                      </a></li>
                    </ul>
                  </div>
                </div>
                </div>
            </div>
            {% empty %}
            <h4>No hay articulos disponibles</h4>
            {% endfor %}
        </div>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="es-ar">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} Blog G13 {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'favicon_80.png' %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}"> -->
    <link rel="stylesheet" href="{% static 'assets/css/g13css.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.18/dist/sweetalert2.min.css" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.18/dist/sweetalert2.all.min.js"></script>
    <script src="https://kit.fontawesome.com/f31b8a5276.js" crossorigin="anonymous"></script>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>
    <script language="text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0;
      function clearField(t){                   
      if(! cleared[t.id]){                      
          cleared[t.id] = 1;  
          t.value='';         
          t.style.color='#fff';
          }
      }
    </script>
  </head>
  <body>
    {% if messages %}
        {% for m in messages %}
          {% if m.tags == 'success' %}
              <script>
                suceso("{{ m }}", "")
              </script>
          {% else %}
              <script>
                alert("{{ m }}", "")
              </script>
          {% endif %}
      {% endfor %}
    {% endif %}
    {% include "header.html" %}
    <br>
    {% block contenido %}
    {% endblock %}

    {% include "footer.html" %}
  </body>
</html>

templates/centroizquierda.html
{% load static %}

<section class="blog-posts">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">
              {% for articulo in home %}
              <div class="col-lg-12">
                <div class="blog-post">
                  <div class="blog-thumb">
                    <img src="{{ articulo.imagen.url}}" width="300" height="600" alt="">
                  </div>
                  <div class="down-content">
                    <span>{{articulo.categoria}}</span>
                    <a href="{% url 'apps.articulo:leer_articulo' articulo.id %}"><h4>{{ articulo.titulo }}</h4></a>
                    <ul class="post-info">
                      <li><a href="#">{{articulo.fecha_hora}}</a></li>
                      <li><a href="#">Comentarios: {{ articulo.comentarios.count }}</a></li>
                    </ul>
                    <p>{{articulo.resumen}}</p>
                    <div class="post-options">
                      <div class="row">
                        <div class="col-6">
                          <ul class="post-share">
                            <li><i class="fa fa-share-alt"></i></li>
                            <li><a href="#">Facebook</a>,</li>
                            <li><a href="#"> Twitter</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              <div class="col-lg-12">
                <div class="main-button">
                  <a href="{% url 'apps.articulo:articulos' %}">Ver todos los artículos</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            <div class="row">
              <div class="col-lg-12">
                <div class="sidebar-item search">
                  <form id="search_form" name="gs" method="GET" action="#">
                    <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
                  </form>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                  <div class="sidebar-heading">
                    <h2>Blogs más recientes</h2>
                  </div>
                  <div class="content">
                    <ul>
                      {% for articulo in articulos|slice:":3" %}
                        <li><a href="{% url 'apps.articulo:leer_articulo' articulo.id %}">
                          <h5>{{ articulo.titulo }}</h5>
                          <span>{{ articulo.fecha_hora }}</span>
                        </a></li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item categories">
                  <div class="sidebar-heading">
                    <h2>Categories</h2>
                  </div>
                  <div class="content">
                    {% for articulo in articulos|slice:":7" %}
                    <ul>
                      <li><a href="#">{{ articulo.categoria }}</a></li>
                    </ul>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div><!---->
              </div>
            </div>
          </div>
        </div>
    </div>
</section>

templates/contactenos.html
{% extends 'home.html' %}
{% load static %}

{% block title %} Contáctenos {% endblock %}

{% block contenido %}

    {% include 'header.html' %}

    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>CONTÁCTENOS</h4>
                <h2>Manténgase en contacto con nosotros!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>


    <section class="contact-us">
      <div class="container">
        <div class="row">
        
          <div class="col-lg-12">
            <div class="down-contact">
              <div class="row">
                <div class="col-lg-8">
                  <div class="sidebar-item contact-form">
                    <div class="sidebar-heading">
                      {% block contacto %}
                      {% endblock %}
                    </div>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="sidebar-item contact-information">
                    <div class="sidebar-heading">
                      <h2>Información de contacto</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li>
                          <h5>123-456-789</h5>
                          <span>NÚMERO DE TELÉFONO</span>
                        </li>
                        <li>
                          <h5>info@compañia.com</h5>
                          <span>EMAIL</span>
                        </li>
                        <li>
                          <h5>Nación, localidad 
                          	<br>Calle, número de calle</h5>
                          <span>DIRECCIÓN</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="col-lg-12">
            <div id="map">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d113289.01764934915!2d-59.077745628938615!3d-27.46048492949619!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450c62a6f5f70b%3A0xf03ac86511c2cd6d!2sResistencia%2C%20Chaco!5e0!3m2!1ses-419!2sar!4v1689234008178!5m2!1ses-419!2sar" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          
        </div>
      </div>
    </section>

{% include 'footer.html' %}

{% endblock contenido %}

templates/contacto.html
{% extends 'contactenos.html' %}


{% block contacto %}

    <div class="container">

        <h1>{{ Mensaje }}</h1>
        <form action="" method="POST">
            {% csrf_token %}

                    {{ form.as_p }}

                <input type="submit" id="myButton" value="Enviar" >

        </form>


    </div>

{% endblock contacto %}

templates/footer.html
{% load static %}
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="social-icons">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Linkedin</a></li>
          </ul>
          <div class="copyright-text">
            <p>Copyright 2023 Grupo 13 - Informatorio
            </p>          
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/header.html
{% with namespace=request.resolver_match.namespace url_name=request.resolver_match.url_name %}
{% load static %}
<header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <div class="navbar-brand">
          <h2>
            <a href="{% url 'inicio'%}">
              <img src="{% static 'favicon_80.png' %}" style="max-height:50px">
              Green<em>13</em>
            </a>
          </h2>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if url_name == 'inicio' %} active {% endif %}">
              <a class="nav-link" href="{% url 'inicio'%}">Inicio</a>
            </li> 
            <li class="nav-item {% if url_name == 'nosotros' %} active {% endif %}">
              <a class="nav-link" href="{% url 'nosotros'%}">Nosotros</a>
            </li>
            <li class="nav-item {% if namespace == 'articulo' %} active {% endif %}">
              <a class="nav-link" href="{% url 'articulo:articulos'%}">Publicaciones</a>
            </li>
            <li class="nav-item {% if url_name == 'contacto' %} active {% endif %}">
              <a class="nav-link" href="{% url 'contacto:contacto' %}">Contacto</a>
            </li>
            <li class="nav-item dropdown 
            {% if url_name == 'login' and not user.is_authenticated %} 
              active 
            {% endif %}"
            >
            {% if user.is_authenticated %}
                <!-- Bienvenido {{user.username | upper}} -->
                <a  class="nav-link" href="#" role="button" data-bs-toggle="dropdown">
                  <div class="circular--portrait" style="max-height:60px;">
                    <img src="{{user.foto_perfil.url}}" alt="foto {{user.username}}">
                  </div>
                </a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><a class="nav-link active">¡hola {{user.username}}!</a></li>
                  <li class="dropdown-item"><a class="nav-link" href="{% url 'usuario:perfil' pk=user.id %}?next={{request.path}}">menu usuario</a></li>
                  {% if user.is_superuser or user.is_miembro %}
                  <li class="dropdown-item"><a class="nav-link" href="{% url 'articulo:crear' %}">publicar articulo</a></li>
                  <li class="dropdown-item"><a class="nav-link" href="{% url 'articulo:crearCategoria' %}?next={{request.path}}">crear categoria</a></li>
                  {% endif %}
                  <li class="dropdown-item">
                    <a class="nav-link warning" href="{% url 'usuario:logout' %}">
                    Cerrar Sesion
                    </a>
                  </li>
                </ul>
            {% else %}
                <a class="nav-link" href="{% url 'usuario:login'%}?next={{request.path}}">Iniciar Sesion</a>
            {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
{%endwith%}

templates/home.html
{% load static %}

<!doctype html>
<html lang="es-ar">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="TemplateMo">
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

  <title>{% block title %} Página de Inicio {% endblock title %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


  <!-- Additional CSS Files -->
  <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--
-->
</head>
<body>

{% block contenido %}



{% endblock contenido %}
</body>

</html>

templates/index.html
<<<<<<< HEAD
{% extends "base.html" %}
{% load articulo_tags %}
{% block inicio_nav %} 
<li class="nav-item active">
{% endblock inicio_nav %}
{% block contenido %}
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
{% block articulo %}
{% include "banner.html" %}
<section class="blog-posts-with-banner blog-posts">
      <div class="container">
        <div class="row mt-5">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                {% for articulo in articulos %}
                {% include "articulo/articulo_resumen.html" %}
                {% empty %}
                <h3>No se han publicado articulos</h3>
                {% endfor %}
              </div>
            </div>
            <div class="col-lg-12">
              <div class="main-button">
                <a href="{% url 'articulo:articulos' %}">Ver todos</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    {% include 'articulo/busqueda_form.html' %}
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Publicaciones recientes</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for articulo in articulos %}
                        <li><a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}">
                          <h5>{{articulo.titulo}}</h5>
                          <span>{{articulo.fecha}}</span>
                        </a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
        {% include "articulo/categorias.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock  %}
{% endblock %}
=======
{% extends 'home.html' %} <!--heredando de home.html-->
{% load static %} <!--esto se hace para cargar los archivos estaticos de la carpeta static-->

{% block contenido %}

{% include "header.html" %}

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="preloader">
      <div class="jumper">
          <div></div>
          <div></div>
          <div></div>
      </div>
  </div>  
  <!-- ***** Preloader End ***** -->

<!--DE ACA SAQUE EL HEADER -->

  <!-- Page Content -->
<!--DE ACA SAQUE EL BANNER-->

 {% include "banner.html" %}

<!--DE ACA SAQUE EL BUSCADOR Y ETIQUETAS-->

 {% include "centroizquierda.html" %}



<!--DE ACA SAQUE EL FOOTER-->

 {% include "footer.html" %}






  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Additional Scripts -->
  <script src="{% static 'assets/js/custom.js' %}"></script>
  <script src="{% static 'assets/js/owl.js' %}"></script>
  <script src="{% static 'assets/js/slick.js' %}"></script>
  <script src="{% static 'assets/js/isotope.js' %}"></script>
  <script src="{% static 'assets/js/accordions.js' %}"></script>

  <script language = "text/Javascript"> 
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t){                   //declaring the array outside of the
    if(! cleared[t.id]){                      // function makes it static and global
        cleared[t.id] = 1;  // you could use true and false, but that's more typing
        t.value='';         // with more chance of typos
        t.style.color='#fff';
        }
    }
  </script>

</body>


{% endblock contenido %}


>>>>>>> origin/Dario

templates/nosotros.html
{% extends "index.html" %}
{% load static %}
{% block contenido %} 
<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>NOSOTROS</span>
              <h4>Aqui encontrara informacion sobre nosotros</p>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="about-us">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <img src="assets/images/about-us.jpg" alt="">
        <p>Somos un grupo apasionado de personas comprometidas con el medio ambiente y la sostenibilidad. Nuestra misión es difundir información, consejos prácticos y soluciones innovadoras para promover la conciencia ambiental en la sociedad.
          Hemos logrado convertir nuestra visión en realidad gracias a un curso de programación dictado por "El Informatorio” en su edición 2023". A través de este curso, adquirimos las habilidades y conocimientos necesarios para diseñar y desarrollar nuestro propio blog dedicado al medio ambiente.
          Encontrarás una amplia variedad de publicaciones relacionadas con temas ambientales y ecológicos. Desde artículos sobre cambio climático, conservación de la biodiversidad, energías renovables, hasta consejos para llevar un estilo de vida más sostenible en el día a día.</p>
          
          <p>Te invitamos a unirte a nuestra comunidad en línea y ser parte del movimiento hacia un mundo más sostenible. Juntos, podemos marcar la diferencia y trabajar por un futuro más verde y próspero para todos.
            ¡Gracias por visitar "GREEN13" y ser parte de este emocionante viaje hacia un planeta más consciente y saludable!</p>
        <div class="center">
          <a href="https://empleo.chaco.gob.ar/informatorio#/"  target="blank"><img src="{% static 'informatorio.png' %}" style="max-height:150px; width:auto;" alt="Logo informatorio"></a>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock %}    