apps/articulo/urls.py
from django.urls import  path

from apps.comentario.views import  registrarComentario, registrarRespuestaAComentario
from .views import  ArticuloBusquedaView, ArticuloListView, ArticuloResumidoView, AutorListView, BorrarArticuloView, BorrarCategoriaView, CategoriaListView, ArticuloView,  CrearArticulo, CrearCategoria, EditarArticulo

app_name = 'articulo'

urlpatterns = [
    path('articulos/', ArticuloListView.as_view(), name='articulos'),
    path('articulo/<int:id>/',ArticuloView.as_view(), name='mostrarArticulo'),
    path('articulo/crear/',CrearArticulo.as_view(), name='crear'),
    path('articulo_resumido/<int:id>/',ArticuloResumidoView.as_view(), name='articulo_resumido'),
    path('articulo/<int:id>/comentar/', registrarComentario, name='comentar'),
    path('articulo/<int:pk>/editar/', EditarArticulo.as_view(), name='editar'),
    path('categoria/<int:pk>/', CategoriaListView.as_view(), name='categoria'),
    path('autor/<int:pk>/', AutorListView.as_view(), name='autor'),
    path('articulo/buscar/',ArticuloBusquedaView.as_view(), name='buscar'),
    path('articulo/<int:id>/responder/', registrarRespuestaAComentario, name='responder'),
    path('categoria/crear/', CrearCategoria.as_view(), name='crearCategoria'),
    path('categoria/<int:pk>/borrar/', BorrarCategoriaView.as_view(), name='borrarCategoria'),
    path('articulo/<int:pk>/borrar/', BorrarArticuloView.as_view(), name='borrar'),
]

apps/usuario/urls.py
from django.urls import  path
from django.contrib.auth.decorators import permission_required
from apps.usuario.views import CambiarEstadoView, CambiarRolView, LoginUsuario, LogoutUsuario, UpdateUsuarioView, VerUsuariosView, registrarUsuario, VerPerfilUsuario


app_name = 'usuario'

urlpatterns = [
    path('usuario/registro/', registrarUsuario.as_view(), name = 'registro'),
    path('usuario/login/', LoginUsuario.as_view(), name='login'),
    path('usuario/logout/', LogoutUsuario.as_view(), name='logout'),
    path('usuario/<int:pk>/actualizar/', UpdateUsuarioView.as_view(), name="actualizar"),
    path('usuario/<int:pk>/ver_perfil/', VerPerfilUsuario.as_view(), name="perfil"),
    path('usuario/usuarios/', VerUsuariosView.as_view(), name="usuarios"),
    path('usuario/estado/<int:pk>', CambiarEstadoView.as_view(), name="cambiar_estado"),
    path('usuario/cambiarrol/<int:pk>', CambiarRolView.as_view(), name="cambiar_rol"),
]

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from .views import IndexView, registration_success, sobre_nosotros

urlpatterns = [
    path('jpqifepfnapkjdfnapdjk/', admin.site.urls),
    path('',IndexView.as_view(), name = "inicio"),
    path('nosotros/', sobre_nosotros, name="nosotros"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("acounts/registration/success/",registration_success, name='registration_success'),
    path('', include('apps.articulo.urls')),
    path('', include('apps.usuario.urls')),
    path('', include('apps.comentario.urls')),
    path('', include('apps.contacto.urls')),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/comentario/models.py
from datetime import datetime
from typing import Iterable, Optional
from django.db import models
from apps.articulo.models import Articulo
from apps.usuario.models import Usuario

# Create your models here.

class Comentario(models.Model):
    
    contenido = models.CharField(
        max_length=200, 
        verbose_name='Texto', 
        help_text='Ingrese aqui su comentario',
        default = ''
        )
    articulo = models.ForeignKey(
        Articulo, 
        on_delete = models.CASCADE, 
        verbose_name = 'Articulo',
        null = True,
        blank = True
        )
    creado = models.DateTimeField(
        editable = False, 
        verbose_name = "Fecha de publicacion"
        )
    comentario_padre = models.ForeignKey(
        "self",
        on_delete = models.CASCADE, 
        verbose_name = 'Comentario',
        null = True,
        blank = True
        )
    creado_por = models.ForeignKey(
        Usuario,
        on_delete = models.CASCADE,
        null=True,
        blank=True,
        verbose_name="creador", 
    )
    is_active = models.BooleanField(
        default=True,
    )    
    
    def __str__(self) -> str:
        return self.contenido
    
    def save(self, *args, **kwargs):
        self.creado = datetime.now()
        return super().save(*args, **kwargs)

apps/articulo/forms.py
from django.forms import FileInput, ModelForm, TextInput, Textarea 
from apps.articulo.models import Articulo, Categoria

class ArticuloCreationForm(ModelForm):

    class Meta:
        model = Articulo
        widgets = {
            'titulo' : TextInput(attrs={'placeholder': 'Ingrese su titulo'}),
            'resumen' : TextInput(attrs={'placeholder': 'Ingrese aqui su resumen'}),
            'contenido' : Textarea(attrs={'rows': 6, 'placeholder': 'Ingrese aqui el articulo'}),
            'imagen': FileInput(),
        }
        exclude = ['creado_por', 'fecha', 'modificado', 'is_active']
        
        
class CategoriaForm(ModelForm):
    
    class Meta:
        model = Categoria
        exclude = ['pk']
        widgets = {
            'categoria' : TextInput(attrs={'placeholder': 'Ingrese su categoria', 'max_length' : 50}),
       
        }
        exclude= ['is_active']

apps/articulo/views.py
from typing import Optional
from django.http import HttpRequest 
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import CreateView, ListView
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from apps.articulo.forms import ArticuloCreationForm, CategoriaForm
from apps.comentario.forms import ComentarioCreationForm
from apps.comentario.models import Comentario
from apps.usuario.models import Usuario

from .models import Articulo, Categoria

# Create your views here.



class ArticuloView(View):
    
    def get(self, request, id):
        articulo = Articulo.objects.filter(is_active = True).get(id=id)
        articulos = Articulo.objects.filter(is_active = True).order_by('-fecha','-id')[:5]
        comentarios = Comentario.objects.filter(is_active = True, articulo = articulo)
        categorias = Categoria.objects.all()
        cant_comentarios = comentarios.count()
        form = ComentarioCreationForm()
        context = { 
                'articulos_banner' : articulos,
                'articulo' : articulo,
                'cant_comentarios' : cant_comentarios,
                'comentarios' : comentarios,
                'categorias' : categorias,
                'form' : form,
                   }
        return render(request, 'articulo/articulo_mostrar.html', context)
   
   
        
class ArticuloResumidoView(View):

    def get(self, request, id):
        articulo = Articulo.objects.get(id=id)
        categorias = Categoria.objects.all()
        context = { 
                'articulo' : articulo,
                'categorias' : categorias
                   }
        return render(request, 'articulo/articulo_resumen.html', context)



class EditarArticulo(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    model = Articulo
    form_class = ArticuloCreationForm
    template_name = 'articulo/articulo_editar.html'
    success_url = ''
    def post(self, request, *args, **kwargs):
        messages.success(request, "Articulo actualizado correctamente")
        return super().post(request, *args, **kwargs)



class CrearArticulo(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    

    form_class = ArticuloCreationForm
    template_name = 'articulo/articulo_crear.html'
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    def form_valid(self, form):
        if form.is_valid:
            form.instance.creado_por = self.request.user
            messages.success(self.request, "Articulo creado exitosamente")
            return super().form_valid(form)
        else:
            messages.error(self.request, "Error en la validacion")
            return render(self.request, 'articulo/articulo_crear.html', {'form': form})



class ArticuloListView(ListView):
    
    model = Articulo
    paginate_by = 4
    template_name = 'articulo/articulos_todos.html'
    cantidad_registros = 0
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articulos_banner'] = Articulo.get_articulos_mas_comentados()
        context['categorias'] = Categoria.objects.all()
        context['registros'] = self.cantidad_registros
        return context
    
    def get_queryset(self):
        articulos = Articulo.objects.filter(is_active=True).order_by('-fecha')
        self.cantidad_registros = articulos.count()
        return articulos



class CategoriaListView(ListView):
    
    model = Articulo
    paginate_by = 4
    template_name = 'articulo/articulos_todos.html'
    cantidad_registros = 0
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registros'] = self.cantidad_registros
        context['categorias'] = Categoria.objects.all()
        context['categoria'] = Categoria.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self):
        articulos = Articulo.objects \
                .filter(is_active=True, categoria=Categoria.objects.get(id=self.kwargs['pk'])) \
                .order_by('-fecha')
        self.cantidad_registros = articulos.count()
        return articulos
    
class AutorListView(ListView):
    
    model = Articulo
    paginate_by = 4
    template_name = 'articulo/articulos_todos.html'
    cantidad_registros = 0
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registros'] = self.cantidad_registros
        context['categorias'] = Categoria.objects.all()
        context['autor'] = Usuario.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self):
        articulos = Articulo.objects \
                .filter(is_active=True, creado_por=Usuario.objects.get(id=self.kwargs['pk'])) \
                .order_by('-fecha')
        self.cantidad_registros = articulos.count()
        return articulos
        


class ArticuloBusquedaView(ListView):
    
    model = Articulo
    paginate_by = 4
    template_name = 'articulo/articulos_todos.html'
    ordering = '-fecha'
    registros = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        context['filter'] = self.request.GET.get('filter', '')
        context['registros'] = self.registros
        context['orderby'] = self.request.GET.get('orderby', '-fecha')        
        return context

    def get_queryset(self):
        filter_val = self.request.GET.get('filter')
        order = self.request.GET.get('orderby')
        if not order:
            order = '-fecha'
        if not filter_val:
            filter_val = ''
        new_context = Articulo.objects  \
            .filter(    \
            Q(titulo__icontains=filter_val) | Q(resumen__icontains=filter_val) | Q(contenido__icontains=filter_val))    \
            .order_by(order)
        self.registros = new_context.count()
        return new_context




class CrearCategoria(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    
    form_class = CategoriaForm
    template_name = 'articulo/categoria_crear.html'
     
     
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False
     
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')
        return context    
    
    def form_valid(self, form):
        if form.is_valid:
            messages.success(self.request, "Categoria agregada exitosamente")
            self.success_url = self.request.POST.get('next') 
            return super().form_valid(form)
        else:
            messages.error(self.request, "Error en la validacion")
            return render(self.request, 'articulo/articulo_crear.html', {'form': form}) 
    
        
        
class BorrarArticuloView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False
    
    model = Articulo
    template_name = 'articulo/articulo_borrar.html'
    success_url = reverse_lazy('articulo:articulos')
    
    def get_success_url(self) -> str:
        messages.success(self.request, "Articulo borrado exitosamente")
        return super().get_success_url()
    
   
    
class BorrarCategoriaView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    def test_func(self):
        if self.request.user.is_active and (self.request.user.is_miembro or self.request.user.is_superuser):
            return True
        else:
            return False

    model = Categoria
    template_name = 'articulo/categoria_borrar.html'
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['next'] = self.request.GET.get('next')
        return ctx
    
    def post(self, request: HttpRequest, *args, **kwargs):
        self.success_url = request.POST.get('next')
        return super().post(request, *args, **kwargs)
    
    def get_success_url(self) -> str:
        messages.success(self.request, "Categoria borrada exitosamente")
        return super().get_success_url()

templates/articulo/articulo.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Articulo {% endblock %}
{% block contenido %}
{% include "header.html" %}

<main>
  <h1> Página de Articulo</h1>
</main>

  <section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="blog-post">
                      {% for articulo in articulos %}
                      <div class="blog-thumb">
                        <img src="{{ articulo.imagen.url }}" width="400" height="550" alt=""><!---->
                      </div>
                      <div class="down-content"> <!---->
                        <span><a href="{{ articulo.contenido }}">{{ articulo.categoria }}</a></span>
                           <a href="{% url 'articulo:articulo' pk=articulo.id %}"><h4> {{ articulo.titulo }}</h4></a>
                        <ul class="post-info">
                          <li><a href="#">{{ articulo.publicado }}</a></li>
                          <li><a href="#">Aca van la cantidad de comentarios</a></li>
                        </ul>
                        <p>{{ articulo.resumen }}.
                        <div class="post-options">
                          <div class="row">
                            <div class="col-6">
                              <ul class="post-share">
                                <li><i class="fa fa-share-alt"></i></li>
                                <li><a href="#">Facebook</a>,</li>
                                <li><a href="#"> Twitter</a></li>
                                <div class="row">
                                    {% if user.is_superuser %}
                                    <a class="btn btn-succes btn-lg" 
                                      href="{% url 'articulo:eliminar' pk=articulo.pk %}"> Eliminar articulo</a>
                                      <a class="btn btn-succes btn-lg" 
                                      href="{% url 'articulo:crear' %}"> Crear articulo</a>
                                    {% endif %}
                                </div>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% empty %}
                      <li>No hay articulos</li>
                      {% endfor %}
                    </div>
                  </div>
                <div class="col-lg-12">
                  <div class="main-button">
                    <a href="{% url 'articulo:articulos' %}">Ver todos los artículos</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
  </section>

{% include "footer.html" %}


{% endblock contenido %}

templates/articulo/articulo_mostrar.html
{% extends "index.html"%}
{% block title %} Blog G13 - Articulo {% endblock %}
{% block articulo %}

<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>ARTICULO</span>
              <h4>Aqui encontrara los detalles del articulo</p>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="blog-posts grid-system">
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-8">
        <div class="all-blog-posts">
          <div class="row">
          <div class="row">
            <div class="col-lg-12">
              <div class="blog-post">
                <div class="blog-thumb">
                  <img src="{{articulo.imagen.url}}" alt="">
                </div>
                {% if user.is_superuser or user.is_miembro %}
                <a href="{% url 'articulo:editar' pk=articulo.id %}">
                 <small>Editar</small>
                </a>
                <small>|</small>
                <a href="{% url 'articulo:borrar' pk=articulo.id %}">
                  <small>Borrar</small>
                </a>
                {% endif %}
                <div class="down-content">
                  <a href="{% url 'articulo:categoria' pk=articulo.categoria.pk %}">
                  <span>{{articulo.categoria}}</span></a>
                  <a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}"><h4>{{articulo.titulo}}</h4></a>
                  <ul class="post-info">
                    <li><a href="{{ articulo.creado_por.get_link_verperfil }}">{{articulo.creado_por}}</a></li>
                    <li><a href="#">{{articulo.fecha}}</a></li>
                    <li><a href="#">{{articulo.comentario_set.all.count }} Comentarios</a></li>
                  </ul>
                  <p>{{articulo.contenido}}</p>
                  <div class="post-options">
                    <div class="row">
                      <div class="col-6">
                        <ul class="post-tags fa-xl">
                          <li>
                            <i class="fa-solid fa-xl fa-tag"></i>
                            <a href="{% url 'articulo:categoria' pk=articulo.categoria.pk %}">{{articulo.categoria}}</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                      <div class="col-6">
                        <ul class="post-share">
                          <li><i class="fa fa-share-alt fa-xl"></i></li>
                          <li><a href="https://www.facebook.com/sharer/sharer.php?u={{request.get_full_path}}">Facebook</a>,</li>
                          <li><a href="#"> Twitter</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% include "../comentario/comentarios.html" %}
            {% if user.is_authenticated  %}
            {% include "../comentario/form-comentarios.html" %}
            {% else %}
            <small>Para comentar ustede debe <a href="{% url 'usuario:login' %}?next={{request.path}}">iniciar sesion</a> o <a href="{% url 'usuario:registro' %}?next={{request.path}}">registrarse</a></small>
            {% endif %}
          </div>
      </div>
      <div class="col-lg-4">
        <div class="sidebar">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item search">
                {% include 'articulo/busqueda_form.html' %}
              </div>
            </div>
            <div class="col-lg-12">
              <div class="sidebar-item recent-posts">
                <div class="sidebar-heading">
                  <h2>Posteos recientes</h2>
                </div>
                <div class="content">
                  <ul>
                    <!-- Aca los ultimos posteos -->
                    {% for articulo in articulos_banner %}
                    <li><a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}">
                      <h5>{{articulo.titulo}}</h5>
                      <span>{{articulo.fecha}}</span>
                    </a></li>
                    {% endfor %}
                    <!-- aca finalizan los ultimos posteos -->
                  </ul>
                </div>
{% include "articulo/categorias.html" %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/articulo/articulo_resumen.html
{% load articulo_tags %}
<div class="col-lg-12">
    <div class="blog-post">
      <div class="blog-thumb">
        <img src="{{ articulo.imagen.url }}" alt="" class="img-lista-articulo">
      </div>
      <div class="down-content">
        <span>{{articulo.categoria}}</span>
        <a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}"><h4>{{ articulo.titulo }}</h4></a>
        <ul class="post-info">
          <li><a href="{% url 'articulo:autor' pk=articulo.creado_por.id %}">{{articulo.creado_por}}</a></li>
          <li><a href="#">{{articulo.fecha}}</a></li>
          <li>
            <a href="">
            {% if articulo.comentario_set.all|is_active|length == 0 %}
            sin comentarios
            {% else %}
            {{articulo.comentario_set.all|is_active|length}} {%if articulo.comentario_set.all|is_active|length == 1%}comentario{%else%}comentarios{%endif%}
            {% endif %}
            </a>
          </li>
        </ul>
        {% if user.is_superuser or user.is_miembro %}
        <a href="{% url 'articulo:editar' pk=articulo.id %}">
         <small>Editar</small>
        </a>
        <small>|</small>
        <a href="{% url 'articulo:borrar' pk=articulo.id %}">
          <small>Borrar</small>
        </a>
        {% endif %}
        <p>{{articulo.resumen}}</p>
        <div class="post-options">
          <div class="row">
            <div class="col-6">
              <ul class="post-tags">
                <li><i class="fa-solid fa-xl fa-tag"></i>
                  <a href="{% url 'articulo:categoria' pk=articulo.categoria.pk %}">{{articulo.categoria}}</a>
                </li>
              </ul>
            </div>
            <div class="col-6">
              <ul class="post-share">
                <li><i class="fa-solid fa-xl fa-share-alt"></i></li>
                <li><a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" target="blank">Facebook</a>,</li>
                <li><a href="#"> Twitter</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/articulo/articulos_todos.html
{% extends "index.html"%}
{% block title %} Blog G13 - Articulos {% endblock %}
{% block articulo %}
{% load articulo_tags %}

<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>Noticas</span>
              <h4>Aqui todas las noticias
                <p style="color:lightgrey">
                  {% if categoria %}
                  Categoria '{{categoria|upper}}':
                  {% endif %}
                  {% if autor %}
                  Publicaciones de {{autor|upper}}:
                  {% endif %}
                  {% if filter %}
                   - Resultados que incluyen '{{filter}}':
                  {% endif %}
                  {{registros}} registros
                </p>
              </h4>
            </div>
            <div class="col-lg-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

<section class="blog-posts grid-system">
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-8">
        <div class="">
          <div class="row">
<!-- Aca en esta seccion empiezan los articulos -->
            {% for articulo in page_obj %}
            <div class="col-lg-6">
              <div class="blog-post">
                <div class="blog-thumb">
                  <img src="{{ articulo.imagen.url }}" alt="">
                </div>
                {% if user.is_superuser or user.is_miembro %}
                <a href="{% url 'articulo:editar' pk=articulo.id %}">
                 <small>Editar</small>
                </a>
                <small>|</small>
                <a href="{% url 'articulo:borrar' pk=articulo.id %}">
                  <small>Borrar</small>
                </a>
                {% endif %}
                <div class="down-content">

                  <a href="{% url 'articulo:categoria' pk=articulo.categoria.pk %}">
                  <span>{{ articulo.categoria }}</span></a>
                  <a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}"><h4>{{ articulo.titulo }}</h4></a>
                  <ul class="post-info">
                    <li><a href="{% url 'articulo:autor' pk=articulo.creado_por.id %}">{{ articulo.creado_por }}</a></li>
                    <li><a href="#">{{ articulo.fecha }}</a></li>
                    <li><a href="#">{{articulo.comentario_set.all.count }} Comentarios</a></li>
                  </ul>
                  <p>{{ articulo.resumen }}</p>
                  <div class="post-options">
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}

<!-- Aca va la parte de paginacion y demas hierbas -->
            <div class="col-lg-12">
              <ul class="page-numbers">
                {% if page_obj.has_previous %}
                <li>
                  <a href="?page=1{% if orderby %}&orderby={{orderby}}{% endif %}{% if filter %}&filter={{filter}}{% endif %}">
                    <i class="fa-solid fa-xl fa-angles-left"></i>
                  </a>
                  <a href="?page={{ page_obj.previous_page_number }}{% if orderby %}&orderby={{orderby}}{% endif %}{% if filter %}&filter={{filter}}{% endif %}">{{ page_obj.previous_page_number }}</a>
                </li>
                {% endif %}
                <li class="active">
                  <a href="">{{ page_obj.number }}</a>
                </li>
                {% if page_obj.has_next %}
                <li>
                  <a href="?page={{ page_obj.next_page_number }}{% if orderby %}&orderby={{orderby}}{% endif %}{% if filter %}&filter={{filter}}{% endif %}">{{ page_obj.next_page_number }}</a>
                  <a href="?page={{ page_obj.paginator.num_pages }}{% if orderby %}&orderby={{orderby}}{% endif %}{% if filter %}&filter={{filter}}{% endif %}" sytle="color:orange;"><i class="fa-solid fa-xl fa-angles-right"></i></a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="sidebar">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item search">
                {% include 'articulo/busqueda_form.html' %}
              </div>
            </div>
            <!-- Comienzan los ultimos posteos -->
            <div class="col-lg-12">
              <div class="sidebar-item recent-posts">
                <div class="sidebar-heading">
                  <h2>Posteos recientes</h2>
                </div>
                <div class="content">
                  <ul>
                    {% for articulo in articulos_banner %}
                    <li><a href="{% url 'articulo:mostrarArticulo' id=articulo.id %}">
                      <h5>{{articulo.titulo}}</h5>
                      <span>{{articulo.fecha}}</span>
                    </a></li>
                    {% endfor %}
                    <!-- aca finalizan los ultimos posteos -->
                  </ul>
                </div>
              </div>
            </div>
            <!-- Aca empiezan las categorias -->
            {% include "articulo/categorias.html" %}
            <!-- Aca terminan las categorias -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/articulo/busqueda_form.html
<form method="get" action="{% url 'articulo:buscar' %}">
  <input class="form-control" placeholder="ingrese aqui su busqueda..." type="text" name="filter" value={{filter}} >
  <p>Ordenar por:</p>
  <select class="form-control" name="orderby" value={{orderby}}>
    <option value="creado_por">Autor (a-z)</option>
    <option value="-creado_por">Autor (z-a)</option>
    <option value="fecha">Fecha: mas antiguos primero</option>
    <option value="-fecha">Fecha: mas recientes primero</option>
    <option value="titulo">Titulo (a-z)</option>
    <option value="-titulo">Titulo (z-a)</option>
  </select>
  <input class="mt-2" type="submit" value="aceptar" style="background-color: #f48840; color:white;">
</form>

templates/articulo/categorias.html
{% load articulo_tags %}
<div class="col-lg-12">
  <div class="sidebar-item tags">
    <div class="sidebar-heading">
      <h2>Categorias</h2>
    </div>
    <div class="content">
      <ul>
        {% for categoria in categorias|is_active %}
        <li >
          <div>
            <a href="{% url 'articulo:categoria' pk=categoria.pk %}">{{categoria.nombre}}</a>
            {% if user.is_superuser or user.is_miembro %}
            <a href="{% url 'articulo:borrarCategoria' pk=categoria.pk %}?next={{request.path}}">
              <button ><span><i class="fa-solid fa-trash"></i></span></button></a>
            {% endif %}
          </div>
        </li>
        {% endfor %}
        <li>
          {% if user.is_superuser or user.is_miembro %}
          <a href="{% url 'articulo:crearCategoria' %}?next={{request.path}}">
            <i class="fa-solid fa-xl fa-add center"></i>
          </a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</div>